### ISSUE TITLE
`pscale auth login` : `Error: error logging in: No such interface “org.freedesktop.DBus.Properties” on object at path /`

### ISSUE THREAD

**Issue by mdatsev** [planetscale/cli#642]
```
# pscale auth login
Error: error logging in: No such interface “org.freedesktop.DBus.Properties” on object at path /
# pscale --version
pscale version 0.133.0 (build date: 2023-03-24T23:38:25Z commit: 42456b8)
```
Running on Ubuntu 20.04.1 LTS on WSL

**Comment by FranciscoMoretti** [comment]
Same issue with pscale version 0.136.0 on Ubuntu 22 on WSL.

**Comment by mscoutermarsh** [comment]
This should now be fixed in [v0.140.0](https://github.com/planetscale/cli/releases/tag/v0.140.0)!

**Comment by phenixcoder** [comment]
This issue still exists in [v0.150.0](https://github.com/planetscale/cli/releases/tag/v0.150.0) when login using `pscale auth login`.

Using Ubuntu 22 over vscode ssh.
